language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
  - pip install numpy
  #- travis_wait pip install scipy
# command to run tests
script: nosetests -s spotpy/examples/tutorial_Parameterlist_iterator.py