language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

  # command to install dependencies
install:
  #- pip install pandas
  - python setup.py install
  - pip install coveralls
  - pip install pathos
  - pip install numpy
  - pip install pytest pytest-pep8 pytest-cov
  #- pip install matplotlib
  #- travis_wait pip install scipy

script:
  - python spotpy/examples/tutorial_rosenbrock.py
  - python spotpy/unittests/test_database.py
  - python spotpy/unittests/test_signatures.py
  - python spotpy/unittests/test_likelihood.py
  - python spotpy/unittests/test_parameter.py
  - python spotpy/unittests/test_setup_parameters.py
  - pip uninstall spotpy -y
  # this is for coveralls.io
  - py.test  spotpy/unittests/test_* spotpy/examples/tutorial_rosenbrock.py  --cov spotpy --cov-report term-missing -v

after_success:
  - coveralls
