language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

  # command to install dependencies
install:
  - python setup.py install
  - pip install coveralls
  - pip install pathos
  - pip install numpy
  - pip install matplotlib
  - pip install pandas==0.23.4
  - pip install scipy
  - pip install click
  - pip install pytest==4.0.1
  - pip install pytest-pep8
  - pip install pytest-cov==2.6.0
  # Use docutils to generate html describe
  - pip install docutils
  - pip install numba


script:
  - pip uninstall spotpy -y
  - py.test  spotpy/unittests/test_* --cov spotpy --cov-report term-missing -v

after_success:
  - coveralls
