language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

  # command to install dependencies
install:
  #- pip install pandas
  - python setup.py install
  - pip install coveralls
  #- pip install matplotlib
  #- travis_wait pip install scipy
# command to run tests

script:
  - coverage run --source=spotpy setup.py spotpy/examples/tutorial_rosenbrock.py
  - python spotpy/examples/tutorial_rosenbrock.py
  - python spotpy/unittests/test_database.py
  - python spotpy/unittests/test_signatures.py
  
  
after_success:
- coveralls
